name: csce642
channels:
  - apple
  - conda-forge
  - defaults
dependencies:
  - abseil-cpp=20211102.0
  - blas=1.0
  - c-ares=1.19.0
  - ca-certificates=2023.05.30
  - grpc-cpp=1.48.2
  - grpcio=1.48.2
  - h5py=3.6.0
  - hdf5=1.12.1
  - krb5=1.19.4
  - libcurl=7.88.1
  - libcxx=14.0.6
  - libedit=3.1.20221030
  - libev=4.33
  - libffi=3.4.4
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libnghttp2=1.46.0
  - libopenblas=0.3.21
  - libprotobuf=3.20.3
  - libssh2=1.10.0
  - llvm-openmp=14.0.6
  - ncurses=6.4
  - numpy-base=1.22.3
  - openssl=1.1.1t
  - pip=23.0.1
  - python==3.10
  - re2=2022.04.01
  - readline=8.2
  - setuptools=67.8.0
  - six=1.16.0
  - sqlite=3.41.2
  - tk=8.6.12
  - wheel=0.38.4
  - xz=5.4.2
  - zlib=1.2.13
  - pip:
      - absl-py==1.4.0
      - astunparse==1.6.3
      - black==23.3.0
      - box2d-py==2.3.5
      - cachetools==5.3.1
      - certifi==2023.5.7
      - charset-normalizer==3.1.0
      - click==8.1.3
      - cloudpickle==2.2.1
      - contourpy==1.0.7
      - cycler==0.11.0
      - farama-notifications==0.0.4
      - filelock==3.12.0
      - flappy-bird-gymnasium==0.2.1
      - flatbuffers==23.5.26
      - fonttools==4.39.4
      - gast==0.4.0
      - google-auth==2.19.1
      - google-auth-oauthlib==1.0.0
      - google-pasta==0.2.0
      - gym==0.26.2
      - gym-notices==0.0.8
      - gymnasium==0.29.0
      - idna==3.4
      - importlib-metadata==6.6.0
      - importlib-resources==5.12.0
      - jax==0.4.12
      - jax-jumpy==1.0.0
      - jinja2==3.1.2
      - joblib==1.2.0
      - keras==2.12.0
      - kiwisolver==1.4.4
      - libclang==16.0.0
      - markdown==3.4.3
      - markupsafe==2.1.3
      - matplotlib==3.7.1
      - ml-dtypes==0.2.0
      - mpmath==1.3.0
      - mypy-extensions==1.0.0
      - networkx==3.1
      - numpy==1.23.5
      - oauthlib==3.2.2
      - opt-einsum==3.3.0
      - packaging==23.1
      - pandas==2.0.2
      - pathspec==0.11.1
      - pillow==9.5.0
      - platformdirs==3.5.1
      - protobuf==4.23.2
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pygame==2.5.0
      - pynput==1.7.6
      - pyobjc-core==9.2
      - pyobjc-framework-applicationservices==9.2
      - pyobjc-framework-cocoa==9.2
      - pyobjc-framework-quartz==9.2
      - pyparsing==3.0.9
      - python-dateutil==2.8.2
      - pytz==2023.3
      - requests==2.31.0
      - requests-oauthlib==1.3.1
      - rsa==4.9
      - scikit-learn==1.2.2
      - scipy==1.10.1
      - swig==4.1.1
      - sympy==1.12
      - tensorflow-macos==2.12.0
      - tensorboard==2.12.3
      - tensorboard-data-server==0.7.0
      - tensorflow-estimator==2.12.0
      - tensorflow-macos==2.12.0
      - tensorflow-metal==1.0.0
      - termcolor==2.3.0
      - threadpoolctl==3.1.0
      - tomli==2.0.1
      - torch==2.0.1
      - torchaudio==2.0.2
      - torchvision==0.15.2
      - typing-extensions==4.6.3
      - tzdata==2023.3
      - urllib3==1.26.16
      - werkzeug==2.3.6
      - wrapt==1.14.1
      - zipp==3.15.0
